name: Backend Deployment to Linux VM
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Backend Deployment to Linux VM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: update and start project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            kill $(lsof -t -i:8080)
            cd ${{ secrets.TARGET }}
            cd backend-P2cinema
            git pull
            mvn clean package
            nohup java -jar target/*.jar &

