name: Build and test Springboot app

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0
        uses: actions/setup-java@v1
        with:
          java-version: 17.0
      - name: Build and test with Maven
        run: |
          mvn clean install
